insert into raids values (nextval('raids_seq'), 'Lower Karazhan Halls');
insert into raids values (nextval('raids_seq'), 'Zul''Gurub');
insert into raids values (nextval('raids_seq'), 'Ruins of Ahn''Qiraj');
insert into raids values (nextval('raids_seq'), 'Onyxia''s Lair');
insert into raids values (nextval('raids_seq'), 'Emerald Sanctum');
insert into raids values (nextval('raids_seq'), 'Molten Core');
insert into raids values (nextval('raids_seq'), 'Blackwing Lair');
insert into raids values (nextval('raids_seq'), 'Temple of Ahn''Qiraj');
insert into raids values (nextval('raids_seq'), 'Naxxramas');

INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Master Blacksmith Rolfen', (SELECT id FROM raids where name = 'Lower Karazhan Halls'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Brood Queen Araxxna', (SELECT id FROM raids where name = 'Lower Karazhan Halls'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Lord Blackwald II', (SELECT id FROM raids where name = 'Lower Karazhan Halls'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Clawlord Howlfang', (SELECT id FROM raids where name = 'Lower Karazhan Halls'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Grizikil', (SELECT id FROM raids where name = 'Lower Karazhan Halls'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Moroes', (SELECT id FROM raids where name = 'Lower Karazhan Halls'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Trash Mobs', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'High Priestess Jeklik', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'High Priest Venoxis', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'High Priestess Mar''li', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Bloodlord Mandokir', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Gri''lek', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Hazza''rah', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Renataki', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Wushoolay', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Gahz''ranka', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'High Priest Thekal', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'High Priestess Arlokk', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Jin''do the Hexxer', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Hakkar', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Muddy Churning Waters', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Jinxed Hoodoo Pile', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Shared Priest Drops', (SELECT id FROM raids where name = 'Zul''Gurub'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Kurinnaxx', (SELECT id FROM raids where name = 'Ruins of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Lieutenant General Andorov', (SELECT id FROM raids where name = 'Ruins of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Rajaxx''s Captains', (SELECT id FROM raids where name = 'Ruins of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'General Rajaxx', (SELECT id FROM raids where name = 'Ruins of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Moam', (SELECT id FROM raids where name = 'Ruins of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Buru the Gorger', (SELECT id FROM raids where name = 'Ruins of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Ayamiss the Hunter', (SELECT id FROM raids where name = 'Ruins of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Ossirian the Unscarred', (SELECT id FROM raids where name = 'Ruins of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Onyxia', (SELECT id FROM raids where name = 'Onyxia''s Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Erennius', (SELECT id FROM raids where name = 'Emerald Sanctum'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Solnius the Awakener', (SELECT id FROM raids where name = 'Emerald Sanctum'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Favor of Erennius', (SELECT id FROM raids where name = 'Emerald Sanctum'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Lucifron', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Magmadar', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Gehennas', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Garr', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Shazzrah', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Baron Geddon', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Golemagg the Incinerator', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Sulfuron Harbinger', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Majordomo Executus', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Ragnaros', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Random Boss Drops', (SELECT id FROM raids where name = 'Molten Core'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Molten Core', (SELECT id FROM raids where name = 'Trash Mobs'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Razorgore the Untamed', (SELECT id FROM raids where name = 'Blackwing Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Vaelastrasz the Corrupt', (SELECT id FROM raids where name = 'Blackwing Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Broodlord Lashlayer', (SELECT id FROM raids where name = 'Blackwing Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Firemaw', (SELECT id FROM raids where name = 'Blackwing Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Ebonroc', (SELECT id FROM raids where name = 'Blackwing Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Flamegor', (SELECT id FROM raids where name = 'Blackwing Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Chromaggus', (SELECT id FROM raids where name = 'Blackwing Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Nefarian', (SELECT id FROM raids where name = 'Blackwing Lair'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'The Prophet Skeram', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'The Bug Family', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Battleguard Sartura', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Fankriss the Unyielding', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Viscidus', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Princess Huhuran', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'The Twin Emperors', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Ouro', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'C''Thun', (SELECT id FROM raids where name = 'Temple of Ahn''Qiraj'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Patchwerk', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Grobbulus', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Gluth', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Thaddius', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Anub''Rekhan', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Grand Widow Faerlina', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Maexxna', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Instructor Razuvious', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Gothik the Harvester', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'The Four Horsemen', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Noth the Plaguebringer', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Heigan the Unclean', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Loatheb', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Sapphiron', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Kel''Thuzad', (SELECT id FROM raids where name = 'Naxxramas'));
INSERT INTO bosses VALUES (nextval('bosses_seq'), 'Naxxramas', (SELECT id FROM raids where name = 'Trash Mobs'));

