insert into raids values (NULL, 'Lower Karazhan Halls');
insert into raids values (NULL, 'Zul''Gurub');
insert into raids values (NULL, 'Ruins of Ahn''Qiraj');
insert into raids values (NULL, 'Onyxia''s Lair');
insert into raids values (NULL, 'Emerald Sanctum');
insert into raids values (NULL, 'Molten Core');
insert into raids values (NULL, 'Blackwing Lair');
insert into raids values (NULL, 'Temple of Ahn''Qiraj');
insert into raids values (NULL, 'Naxxramas');
insert into raids values (NULL, 'Tower of Karazhan');